export const FIND_PRODUCT_BY_ID_REQUEST = "FIND_PRODUCT_BY_ID_REQUEST";
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS";
export const FIND_PRODUCT_BY_ID_FAILURE = "FIND_PRODUCT_BY_ID_FAILURE";

export const FIND_ALL_PRODUCTS_REQUEST = "FIND_ALL_PRODUCTS_REQUEST";
export const FIND_ALL_PRODUCTS_SUCCESS = "FIND_ALL_PRODUCTS_SUCCESS";
export const FIND_ALL_PRODUCTS_FAILURE = "FIND_ALL_PRODUCTS_FAILURE";

export const DELETE_PRODUCT_BY_ID_REQUEST = "DELETE_PRODUCT_BY_ID_REQUEST";
export const DELETE_PRODUCT_BY_ID_SUCCESS = "DELETE_PRODUCT_BY_ID_SUCCESS";
export const DELETE_PRODUCT_BY_ID_FAILURE = "DELETE_PRODUCT_BY_ID_FAILURE";

export const UPDATE_PRODUCT_BY_ID_REQUEST = "UPDATE_PRODUCT_BY_ID_REQUEST";
export const UPDATE_PRODUCT_BY_ID_SUCCESS = "UPDATE_PRODUCT_BY_ID_SUCCESS";
export const UPDATE_PRODUCT_BY_ID_FAILURE = "UPDATE_PRODUCT_BY_ID_FAILURE";

export const CREATE_NEW_PRODUCT_REQUEST = "CREATE_NEW_PRODUCT_REQUEST";
export const CREATE_NEW_PRODUCT_SUCCESS = "CREATE_NEW_PRODUCT_SUCCESS";
export const CREATE_NEW_PRODUCT_FAILURE = "CREATE_NEW_PRODUCT_FAILURE";



